### ISSUE TITLE
Incompatibility with Explorer's Compass + Chaosyr's other mods

### ISSUE THREAD

**Issue by Aninuscsalas** [JustAlittleWolf/SmoothScrollingRefurbished#1]
Tested on 1.20.1 fabric.
Scrolling with a mouse doesn't work with Explorer's Compass, Nature's Compass and Notes custom UIs.

- https://modrinth.com/mod/natures-compass
- https://modrinth.com/mod/explorers-compass
- https://modrinth.com/mod/notes

Log : https://mclo.gs/tIJGHTo

**Comment by JustAlittleWolf** [comment]
Thanks for submitting the issue! The problem is that the mods you listed implement their own scrollList, and override the `render()` method. This prevents my mod from updating the scrollbar every frame but still blocks the vanilla scrolling behaviour. With the fix, it now disables the smooth scrolling feature when an incompatibility is detected, so the scrollbars in your mods now work as intentend (however with vanilla scrolling, not smooth scrolling). To make smooth scrolling work on them as well would require further changes in both the other mods and my mod.
Thanks for brining this issue to my attention!
